[tool.poetry]
name = "linear-cli"
version = "0.1.0"
description = "Linear CLI tool written in Python"
authors = ["Caspar Nettelbladt <caspar.n@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "linear", from = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"
colorama = "^0.4.6"

[tool.poetry.scripts]
linear-cli = "linear.main:cli"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
